name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i --include=optional

      - name: Build Angular app
        run: npm run build

      - name: Prepare deployment files
        run: |
          cp dist/sport-family-site/browser/index.html dist/sport-family-site/browser/404.html
          touch dist/sport-family-site/browser/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/sport-family-site/browser
          branch: gh-pages
          clean: true
